export const getEmptyRecipe = () => {
  return {
    idMeal: '52774',
    strMeal: 'Pad See Ew',
    strMealAlternate: null,
    strCategory: 'Chicken',
    strArea: 'Thai',
    strInstructions:
      "Mix Sauce in small bowl.\r\nMince garlic into wok with oil. Place over high heat, when hot, add chicken and Chinese broccoli stems, cook until chicken is light golden.\r\nPush to the side of the wok, crack egg in and scramble. Don't worry if it sticks to the bottom of the wok - it will char and which adds authentic flavour.\r\nAdd noodles, Chinese broccoli leaves and sauce. Gently mix together until the noodles are stained dark and leaves are wilted. Serve immediately!",
    strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg',
    strTags: 'Pasta',
    strYoutube: 'https://www.youtube.com/watch?v=Ohy1DELF4is',
    strIngredient1: 'rice stick noodles',
    strIngredient2: 'dark soy sauce',
    strIngredient3: 'oyster sauce',
    strIngredient4: 'soy sauce',
    strIngredient5: 'white vinegar',
    strIngredient6: 'sugar',
    strIngredient7: 'water',
    strIngredient8: 'peanut oil',
    strIngredient9: 'garlic',
    strIngredient10: 'Chicken',
    strIngredient11: 'Egg',
    strIngredient12: 'Chinese broccoli',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: '6oz/180g',
    strMeasure2: '2 tbsp',
    strMeasure3: '2 tbsp',
    strMeasure4: '2 tsp',
    strMeasure5: '2 tsp',
    strMeasure6: '2 tsp',
    strMeasure7: '2 tbsp',
    strMeasure8: '2 tbsp',
    strMeasure9: '2 cloves',
    strMeasure10: '1 cup',
    strMeasure11: '1',
    strMeasure12: '4 cups',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: null,
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  }
}
